### ISSUE TITLE
Extra-Life-Overlay: Can we add Team Name, Team Goal and Milestone Indicator to display

### ISSUE THREAD

**Issue by hydechuck-az** [weegeekps/extra-life-overlay#13]
**Describe the bug**
Once I've added the Donor Drive Thermometer "Extra-Life-Overlay" (https://github.com/weegeekps/extra-life-overlay) and entered my Team ID, I can see the Thermometer and my current amount raised. I'm not able to see my Team's Name or our Fundraising Goal, which I think would be very beneficial to all users not just my team.  

**To Reproduce**
1. Go to 'https://github.com/weegeekps/extra-life-overlay'
2. Follow the steps for "Using for a Team....'
3. Add Browser Source in respective OBS Software 

**Expected behavior**
This is a Feature Request, so the expected behavior would be to utilize the surrounding screen real estate around the Thermometer to indicate the Team Name, Team Fundraising $$ Goals and Milestone indicators.

**Screenshots**
Attached two screenshots.
![Team Thermometer(1)](https://user-images.githubusercontent.com/74018003/105079122-38175680-5a4c-11eb-918c-1d10725a39ad.png)
![Team Thermometer](https://user-images.githubusercontent.com/74018003/105079610-e58a6a00-5a4c-11eb-9ca9-bf0973c1fddf.png)

**Streaming Client:**
 - OS: Windows 10 Home Edition 
 - Client Name [Streamlabs OBS]
 - Version [0.26.0]

**Additional context**
This thermometer is a fabulous addition to any participant's overlay, I feel like it could increase the value and usability of the tool if any or all of these features were added to the overlay.

**Comment by weegeekps** [comment]
@hydechuck-az I've added support for showing the team name and showing the fundraising goal. I haven´t added support for milestones yet as that will take a bit more work and these two turned out to be very easy to add.

A sample URL that shows both the team name and goal is:

[https://weegeekps.github.io/extra-life-overlay?team=57119&showTeamName=true&showGoal=true]

Showing the goal also works for individuals as well. Just pass in a Participant ID to `participant` instead of the Team ID.

**Comment by weegeekps** [comment]
@hydechuck-az This request is fully implemented now. I have just pushed a change that adds support for showing participant milestones. Just add `&milestones=true` to your URL. There are a few caveats:

- It only works for participants. This is due to the data not being available for teams.
- It only works if `orientation` is not set. This is due to me not having time to implement it for right orientation. I'm sorry if this is an inconvenience. Please see #21 for more info.

Good luck with your Extra Life efforts this year.
